UPDATE `creature_template` SET `InhabitType` = 4 WHERE `entry` IN (67273, 67590);
UPDATE `creature_template` SET `faction` = 250 WHERE `entry` = 67681;
UPDATE `creature_template` SET `unit_flags` = 512, `faction` = 250, `InhabitType` = 6 WHERE `entry` = 67783;
UPDATE `creature_template` SET `gossip_menu_id` = 15183, `npcflag` = 1, `ScriptName` = "npc_dagger_in_dark_voljin" WHERE `entry` = 67414;
UPDATE `creature_template` SET `faction` = 250, `ScriptName` = "npc_dagger_in_dark_rakgor_bloodrazor" WHERE `entry` = 67266;
UPDATE `creature_template` SET `faction` = 250, `ScriptName` = "npc_dagger_in_dark_grizzle_gearslip" WHERE `entry` = 67782;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_shaman" WHERE `entry` = 67255;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_skinflayer" WHERE `entry` = 67258;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_skulker" WHERE `entry` = 67257;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_oracle" WHERE `entry` = 67256;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_corrupted_darkhatched_slayer" WHERE `entry` = 67832;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_corrupted_dark_hatched_egg" WHERE `entry` = 67798;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_flesh_hunter" WHERE `entry` = 67259;
UPDATE `creature_template` SET `unit_flags` = 512, `faction` = 250, `ScriptName` = "npc_dagger_in_dark_broken_mogu_tablet" WHERE `entry` IN (67862, 67863);
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_broodmaster_noshi" WHERE `entry` = 67264;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_stalactite" WHERE `entry` = 67755;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_mogu_rune" WHERE `entry` = 67686;
UPDATE `creature_template` SET `unit_flags` = 512, `faction` = 250, `ScriptName` = "npc_dagger_in_dark_goblin_cannon" WHERE `entry` = 67694;
UPDATE `creature_template` SET `ScriptName` = "npc_dagger_in_dark_darkhatched_lizard_lord" WHERE `entry` = 67263;
UPDATE `creature_template` SET `unit_flags` = 512, `faction` = 250, `ScriptName` = "npc_dagger_in_dark_spring_saurok_slayer", `InhabitType` = 6 WHERE `entry` = 67706;
UPDATE `creature_template` SET `unit_flags` = 262148 WHERE `entry` IN (67779, 67792);
